<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>annotations</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>RogueDungeonGen</RootNamespace>
    <AssemblyName>rogue_dungeon_gen</AssemblyName>
  </PropertyGroup>

</Project>
